# Generated by Django 2.0.5 on 2018-05-22 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picksong', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picksong',
            new_name='Song',
        ),
    ]
