# Generated by Django 2.0.5 on 2018-05-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picksong', '0002_auto_20180522_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='highest_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lowest_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='key_of_song',
            field=models.TextField(blank=True),
        ),
    ]
